---
- hosts: all
  vars_files:
    - config.yml
  roles:
    - {role: minimal-workstation}
    - {role: workstation, when: workstation | bool}
    - {role: user-config}
    - {role: gnome, when: gnome | bool}
