---
# tasks file for vworkstation

- name: Enable PPAs
  become: yes
  become_method: sudo
  ansible.builtin.command: add-apt-repository -y "{{ item }}"
  loop: "{{ ppas }}"

- name: Install GPG key for SublimeText
  become: true
  become_method: sudo
  ansible.builtin.get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /etc/apt/keyrings/sublimehq-pub.asc
    mode: '0644'
    force: true

- name: Add Sublime repository
  become: true
  become_method: sudo
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/sublimehq-pub.asc] https://download.sublimetext.com/ apt/stable/'
    state: present
    filename: "sublime-text.list"

- name: Update apt cache
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: yes

- name: Install workstation packages
  become: yes
  become_method: sudo
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ workstation_packages }}"

- name: Install downloaded debs
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ deb_downloads }}"

- name: Install workstation snap packages
  become: yes
  become_method: sudo
  community.general.snap:
    name: "{{ item }}"
    state: present
  loop: "{{ workstation_snaps }}"

# - name: Install workstation snap packages (classic)
#   become: yes
#   become_method: sudo
#   community.general.snap:
#     name: "{{ item }}"
#     state: present
#     classic: true
#   loop: "{{ workstation_classic_snaps }}"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpaks
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpaks }}"

- name: Install tailscale using its script
  become: yes
  become_method: sudo
  ignore_errors: yes
  shell: "wget -qO - https://tailscale.com/install.sh | sh"
  args:
    executable: /bin/sh
  failed_when: false

- name: Configure PAM for Yubikey
  become: true
  become_method: sudo
  copy:
    src: common-u2f
    dest: /etc/pam.d/common-u2f

- name: Add Yubikey as auth option
  become: true
  become_method: sudo
  args:
    chdir: /etc/pam.d
  shell:
    cmd: |
      for f in $(grep -l "@include common-auth" *); do
        if [[ $f == *~ ]]; then continue; fi
        if grep -q "@include common-u2f" $f; then continue; fi
        mv $f $f~
        awk '/@include common-auth/ {print "@include common-u2f"}; {print}' $f~ > $f
      done
