---
# tasks file for vworkstation

- name: Enable PPAs
  become: yes
  become_method: sudo
  ansible.builtin.command: add-apt-repository -y "{{ item }}"
  loop: "{{ ppas }}"

- name: Install GPG key for SublimeText
  become: true
  become_method: sudo
  ansible.builtin.get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /etc/apt/keyrings/sublimehq-pub.asc
    mode: '0644'
    force: true

- name: Add Sublime repository
  become: true
  become_method: sudo
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/sublimehq-pub.asc] https://download.sublimetext.com/ apt/stable/'
    state: present
    filename: "sublime-text.list"

- name: Install GPG key for Brave
  become: true
  become_method: sudo
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /etc/apt/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'
    force: true

- name: Add Brave repository
  become: true
  become_method: sudo
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main'
    state: present
    filename: "/etc/apt/sources.list.d/brave-browser-release.list"

- name: Update apt cache
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: yes

- name: Install workstation packages
  become: yes
  become_method: sudo
  ansible.builtin.package:
    name: "{{ workstation_packages }}"
    state: latest

- name: Install downloaded debs
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ deb_downloads }}"

- name: Install workstation snap packages
  become: yes
  become_method: sudo
  community.general.snap:
    name: "{{ item }}"
    state: present
  loop: "{{ workstation_snaps }}"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpaks
  community.general.flatpak:
    name: "{{ flatpaks }}"
    state: present
    method: user

- name: Configure PAM for Yubikey
  become: true
  become_method: sudo
  copy:
    src: common-u2f
    dest: /etc/pam.d/common-u2f

- name: Add Yubikey as auth option
  become: true
  become_method: sudo
  args:
    chdir: /etc/pam.d
  shell:
    cmd: |
      for f in $(grep -l "@include common-auth" *); do
        if [[ $f == *~ ]]; then continue; fi
        if grep -q "@include common-u2f" $f; then continue; fi
        mv $f $f~
        awk '/@include common-auth/ {print "@include common-u2f"}; {print}' $f~ > $f
      done

- name: Download tailscale install script
  ansible.builtin.get_url:
    url: https://tailscale.com/install.sh
    dest: /tmp/install-tailscale.sh
    mode: '0740'

- name: Install tailscale using its script
  become: yes
  become_method: sudo
  ignore_errors: yes
  shell: "/tmp/install-tailscale.sh"
  args:
    executable: /bin/sh
  failed_when: false

- name: Delete downloaded script
  ansible.builtin.file:
    path: /tmp/install-tailscale.sh
    state: absent