---
# tasks file for minimal_workstation
- name: Create the user
  become: yes
  become_method: sudo
  ansible.builtin.user:
    name: "{{ user.name}}"
    comment: "{{ user.full_name }}"
    create_home: True
    shell: /bin/zsh
    state: present

- name: Enable universe and multiverse
  become: yes
  become_method: sudo
  ansible.builtin.command: add-apt-repository -y universe multiverse

- name: Install Git LFS PackageCloud repo using its script
  become: yes
  become_method: sudo
  ignore_errors: yes
  shell: "curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash"
  args:
    executable: /bin/sh
  failed_when: false

- name: Update and upgrade apt packages
  become: true
  become_method: sudo
  apt:
    upgrade: "dist"
    update_cache: yes

- name: Install base packages
  become: yes
  become_method: sudo
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ base_packages }}"

- name: Install snap packages
  become: yes
  become_method: sudo
  community.general.snap:
    name: "{{ item }}"
    state: present
  loop: 
    - "{{ base_snaps }}"

- name: Test for zsh config
  shell: grep -c "^emulate sh -c 'source /etc/profile'" /etc/zsh/zprofile || true
  register: test_grep

- name: Update global zprofile
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/zsh/zprofile
    line: emulate sh -c 'source /etc/profile'
  when: test_grep.stdout == "0"
