---
# tasks file for minimal_workstation
- name: Enable universe and multiverse
  become: yes
  become_method: sudo
  ansible.builtin.command: add-apt-repository -y universe multiverse

- name: Enable snapd (for Linux Mint)
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /etc/apt/preferences.d/nosnap.pref
    state: absent

- name: Update and upgrade apt packages
  become: true
  become_method: sudo
  apt:
    upgrade: "dist"
    update_cache: yes

- name: Install base packages
  become: yes
  become_method: sudo
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: latest

- name: Pause for 1 minute for snap
  ansible.builtin.pause:
    minutes: 1

- name: Run snap info to make sure it works
  ansible.builtin.command: snap list

- name: Install snap packages
  become: yes
  become_method: sudo
  community.general.snap:
    name: "{{ base_snaps }}"
    state: present

- name: Test for zsh config
  shell: grep -c "^emulate sh -c 'source /etc/profile'" /etc/zsh/zprofile || true
  register: test_grep

- name: Update global zprofile
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/zsh/zprofile
    line: emulate sh -c 'source /etc/profile'
  when: test_grep.stdout == "0"

- name: Install GPG key for GitHub CLI
  become: true
  become_method: sudo
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'
    force: true

- name: Add GitHub CLI repository
  become: true
  become_method: sudo
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main'
    state: present
    filename: "github-cli.list"

- name: Install base python packages
  community.general.pipx:
    name: "{{ item }}"
  loop: "{{ base_pips }}"
