---
base_packages:
  - zsh
  - bat
  - myrepos
  - ncdu
  - python3-pip
  - silversearcher-ag
  - sshuttle
  - tig
  - tmux
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - curl
  - btop
  - openssh-server
  - apt-file
  - vim
  - stow
  - fd-find
  - byobu
  - python3-virtualenv
  - snapd
  - pipx

base_snaps:
  - lxd

workstation_packages:
  - pcscd
  - scdaemon
  - openvpn
  - sublime-text
  - input-remapper
  - yubikey-manager
  - yubikey-personalization
  - libpam-yubico
  - libpam-u2f
  - virt-manager
  - syncthing
  - thunderbird
  - flatpak
  - gnome-tweaks
  - gnome-shell-extension-manager
  - deja-dup

pips:
  - black
  - flake8

deb_downloads:
  - https://infinitekind.com/stabledl/current/moneydance_linux_amd64.deb

ppas:
  - ppa:yubico/stable

workstation_snaps:
  - icloud-for-linux
  - nativefier

flatpaks:
  - net.codeindustry.MasterPDFEditor
  - net.lutris.Lutris
  - md.obsidian.Obsidian
  - us.zoom.Zoom
  - com.dropbox.Client
  - com.mojang.Minecraft
  - com.authy.Authy
  - com.bitwarden.desktop
  - com.mattermost.Desktop
  - com.slack.Slack
  - com.spotify.Client
  - com.ticktick.TickTick
  - us.zoom.Zoom
  - org.chromium.Chromium
  - com.valvesoftware.Steam
  - com.github.tchx84.Flatseal

user:
  name: tmoyer
  full_name: Tom Moyer

dotfiles:
  - apps
  - gpg
  - latex
  - misc
  - mr
  - pics
  - ssh
  - tmux
  - vcs
  - zsh
  - subl
  - watson

gpg_key: "0x6B0A28C4075F6051"
