---
base_packages:
  - zsh
  - bat
  - myrepos
  - ncdu
  - python3-pip
  - silversearcher-ag
  - sshuttle
  - tig
  - tmux
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - curl
  - btop
  - openssh-server
  - apt-file
  - vim
  - stow
  - fd-find
  - byobu
  - python3-virtualenv
  - snapd
  - pipx
  - neofetch

base_snaps:
  - lxd

workstation_packages:
  - pcscd
  - scdaemon
  - openvpn
  - sublime-text
  - input-remapper
  - yubikey-manager
  - yubikey-personalization
  - libpam-yubico
  - libpam-u2f
  - virt-manager
  - syncthing
  - flatpak
  - libhidapi-libusb0
  - libxcb-xinerama0
  - libxcb-cursor0
  - brave-browser
  - yakuake

pips:
  - black
  - flake8
  - streamdeck_ui
  - pipenv
  - poetry

deb_downloads:
  - https://infinitekind.com/stabledl/current/moneydance_linux_amd64.deb

ppas:
  - ppa:yubico/stable

workstation_snaps:
  - icloud-for-linux
  - nativefier
  - morgen
  - zoom-client
  - bitwarden
  - mattermost-desktop
  - slack
  - spotify
  - steam
  - mailspring

flatpaks:
  - net.codeindustry.MasterPDFEditor
  - com.dropbox.Client
  - org.prismlauncher.PrismLauncher
  - com.github.tchx84.Flatseal
  - md.obsidian.Obsidian
  - net.lutris.Lutris

user:
  name: tmoyer
  full_name: Tom Moyer

dotfiles:
  - apps
  - gpg
  - latex
  - misc
  - mr
  - pics
  - ssh
  - tmux
  - vcs
  - zsh
  - subl
  - watson
  - streamdeck

gpg_key: "0x6B0A28C4075F6051"
