---
base_packages:
  - zsh
  - bat
  - myrepos
  - ncdu
  - python3-pip
  - silversearcher-ag
  - sshuttle
  - tig
  - tmux
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - curl
  - btop
  - openssh-server
  - apt-file
  - vim
  - stow
  - fd-find
  - byobu
  - python3-virtualenv
  - pipx
  - neofetch
  - fzf
  - prettyping
  - snapd
  - fonts-powerline

base_snaps:
  - lxd

workstation_packages:
  - pcscd
  - scdaemon
  - openvpn
  - sublime-text
  - input-remapper
  - yubikey-manager
  - yubikey-personalization
  - libpam-yubico
  - libpam-u2f
  - syncthing
  - flatpak
  - libhidapi-libusb0
  - libxcb-xinerama0
  - libxcb-cursor0
  - borgbackup
  - ulauncher
  - xdotool
  - solaar
  - xclip
  - gh
  - gnome-shell-extension-manager
  - gnome-tweaks
  - chrome-gnome-shell
  - gnome-calendar

pips:
  - black
  - flake8
  - streamdeck_ui
  - pipenv
  - poetry
  - python-kasa[speedups]
  - borgmatic

deb_downloads:
  - https://github.com/Browsers-software/browsers/releases/latest/download/browsers_amd64.deb
  - https://infinitekind.com/stabledl/current/moneydance_linux_amd64.deb
  - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - https://zoom.us/client/5.15.12.7665/zoom_amd64.deb

ppas:
  - ppa:yubico/stable
  - ppa:agornostal/ulauncher

workstation_snaps:
  - icloud-for-linux
  - bitwarden
  - slack
  - spotify
  - mailspring
  - mattermost-desktop
  - steam

flatpaks:
  - net.codeindustry.MasterPDFEditor
  - com.dropbox.Client
  - org.prismlauncher.PrismLauncher
  - com.github.tchx84.Flatseal
  - net.lutris.Lutris
  - com.github.Murmele.Gittyup

user:
  name: tmoyer
  full_name: Tom Moyer

dotfiles:
  - apps
  - gpg
  - misc
  - mr
  - pics
  - ssh
  - tmux
  - vcs
  - zsh
  - subl
  - watson
  - streamdeck

gpg_key: "0x6B0A28C4075F6051"
