---
base_packages:
  - zsh
  - bat
  - build-essential
  - myrepos
  - ncdu
  - python3-pip
  - silversearcher-ag
  - sshuttle
  - tig
  - tmux
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - curl
  - btop
  - openssh-server
  - apt-file
  - vim
  - stow
  - fd-find
  - byobu

base_snaps:
  - lxd

workstation_packages:
  - flatpak
  - pcscd
  - virtinst
  - scdaemon
  - libpam-yubico
  - libpam-u2f
  - openvpn
  - sublime-text
  - input-remapper
  - texlive-full
  - wl-clipboard
  - xclip
  - yubikey-manager
  - yubikey-personalization
  - yubikey-manager
  - libpam-yubico
  - libpam-u2f
  - waypipe
  - ulauncher
  - wmctrl
  - virt-manager
  - syncthing
  - pavucontrol
  - hexchat
  - thunderbird
  - netclient
  - deja-dup
  - yakuake

pips:
  - black
  - flake8

deb_downloads:
  - https://linux.dropbox.com/packages/ubuntu/dropbox_2020.03.04_amd64.deb
  - https://launcher.mojang.com/download/Minecraft.deb
  - https://repo.steampowered.com/steam/archive/stable/steam_latest.deb
  - https://infinitekind.com/stabledl/current/moneydance_linux_amd64.deb

ppas:
  - ppa:yubico/stable
  - ppa:agornostal/ulauncher

workstation_snaps:
  - authy
  - bitwarden
  - icloud-for-linux
  - mattermost-desktop
  - slack
  - spotify
  - telegram-desktop
  - zotero-snap
  - ticktick
  - zoom-client
  - jabref
  - signal-desktop
  - chromium

flatpaks:
  - net.codeindustry.MasterPDFEditor
  - net.lutris.Lutris
  - md.obsidian.Obsidian
  - us.zoom.Zoom

user:
  name: tmoyer
  full_name: Tom Moyer

dotfiles:
  - apps
  - gpg
  - latex
  - misc
  - mr
  - pics
  - ssh
  - tmux
  - vcs
  - zsh
  - subl
  - watson

gpg_key: "0x6B0A28C4075F6051"
