---
# tasks file for user-config
- name: Clone dotfiles (read-only)
  ansible.builtin.git:
    repo: https://github.com/tommoyer/dotfiles.git
    dest: ${HOME}/.dotfiles

- name: Change remote for dotfiles
  ansible.builtin.command: "git remote set-url origin git@github.com:tommoyer/dotfiles.git"
  args:
    chdir: ${HOME}/.dotfiles

- name: Install python packages
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ pips }}"

- name: Install zimfw using its script
  ignore_errors: yes
  register: zimfw_output
  shell: "curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh"
  args:
    executable: /usr/bin/zsh
  changed_when: "'already exists' not in zimfw_output.stderr"
  failed_when: false

- name: Delete .zshrc and .zimrc
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - ${HOME}/.zshrc
    - ${HOME}/.zimrc

- name: Stow dotfiles
  stow:
    state: latest
    package: '{{ item }}'
    dir: "${HOME}/.dotfiles"
    target: '$HOME'
  loop: "{{ dotfiles }}"

- name: Fix directory permissions
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0700'
  loop:
    - ${HOME}/.gnupg
    - ${HOME}/.ssh

- name: Import GPG public key
  ansible.builtin.command: gpg --batch --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys {{ gpg_key }}

- name: Install zimfw modules
  shell: "source /home/tmoyer/.zim/zimfw.zsh install"
  args:
    executable: /usr/bin/zsh

- name: Change remote for bootstrap
  ansible.builtin.command: "git remote set-url origin git@github.com:tommoyer/bootstrap.git"
  args:
    chdir: ${HOME}/Repos/tommoyer/bootstrap

- name: Configuring Gnome things (1/2)
  ansible.builtin.command: gsettings set org.gnome.evolution-data-server.calendar notify-with-tray true

- name: Configuring Gnome things (2/2)
  ansible.builtin.command: gsettings set org.gnome.mutter center-new-windows true

- name: Create Yubikey setup script
  copy:
    src: finish-yubikey-setup.sh
    dest: ${HOME}/finish-yubikey-setup.sh
    mode: u=rwx,g=r,o=r

- name: Update list of installed applications (1/2)
  ansible.builtin.command: update-desktop-database ${HOME}/.local/share/applications

- name: Update list of installed applications (2/2)
  ansible.builtin.command: update-desktop-database ${HOME}/.local/share/flatpak/exports/share/applications

- name: Set default browser to Junction
  ansible.builtin.command: xdg-settings set default-web-browser re.sonny.Junction.desktop
