---
# tasks file for user-config
- name: Create the user
  become: yes
  become_method: sudo
  ansible.builtin.user:
    name: "{{ user.name }}"
    comment: "{{ user.full_name }}"
    create_home: True
    shell: /usr/bin/zsh
    state: present

- name: Clone dotfiles (read-only)
  ansible.builtin.git:
    repo: https://github.com/tommoyer/dotfiles.git
    dest: ${HOME}/.dotfiles

- name: Change remote for dotfiles
  ansible.builtin.command: "git remote set-url origin git@github.com:tommoyer/dotfiles.git"
  args:
    chdir: ${HOME}/.dotfiles

- name: Install python packages
  community.general.pipx:
    name: "{{ item }}"
  loop: "{{ pips }}"

- name: Install Watson from wheel
  community.general.pipx:
    name: td_watson
    source: https://thomasmoyer.org/td_watson-2.1.0+notes-py2.py3-none-any.whl

- name: Install watson2sf from wheel
  community.general.pipx:
    name: watson2sf
    source: https://thomasmoyer.org/watson2sf-0.1.2-py3-none-any.whl

- name: Create watson directory
  ansible.builtin.file:
    path: ${HOME}/.config/watson
    state: directory
    mode: '0755'

- name: Stow dotfiles
  stow:
    state: latest
    package: '{{ item }}'
    dir: "${HOME}/.dotfiles"
    target: '$HOME'
  loop: "{{ dotfiles }}"

- name: Fix directory permissions
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0700'
  loop:
    - ${HOME}/.gnupg
    - ${HOME}/.ssh

- name: Import GPG public key
  ansible.builtin.command: gpg --batch --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys {{ gpg_key }}

- name: Change remote for bootstrap
  ansible.builtin.command: "git remote set-url origin git@github.com:tommoyer/bootstrap.git"
  args:
    chdir: ${HOME}/Repos/tommoyer/bootstrap

- name: Post-Ansible finish script
  template:
    src: files/finish-setup.sh
    dest: ${HOME}/finish-setup.sh
    mode: u=rwx,g=r,o=r

- name: LXD config preseed file
  copy:
    src: lxd-init.yaml
    dest: ${HOME}/lxd-init.yaml
    mode: u=rwx,g=r,o=r

- name: LXD default profile
  copy:
    src: lxd-default-profile.yaml
    dest: ${HOME}/lxd-default-profile.yaml
    mode: u=rwx,g=r,o=r

- name: Gnome terminal settings
  copy:
    src: gnome_terminal_settings_backup.dconf
    dest: ${HOME}/gnome_terminal_settings_backup.dconf
    mode: u=rwx,g=r,o=r

- name: LXD DNS setup
  become: yes
  become_method: sudo
  copy:
    src: lxd-dns-lxdbr0.service
    dest: /etc/systemd/system/lxd-dns-lxdbr0.service
    mode: u=rwx,g=r,o=r

- name: Enable LXD DNS
  become: yes
  become_method: sudo
  ansible.builtin.command: systemctl daemon-reload

- name: Enable LXD DNS
  become: yes
  become_method: sudo
  ansible.builtin.command: systemctl enable --now lxd-dns-lxdbr0

- name: Install Streamdeck udev rules
  become: yes
  become_method: sudo
  copy:
    src: 70-streamdeck.rules
    dest: /etc/udev/rules.d/70-streamdeck.rules
    mode: u=rw,g=r,o=r

- name: Reload udev rules
  become: yes
  become_method: sudo
  ansible.builtin.command: udevadm control --reload-rules
 
- name: Download pyenv install script
  ansible.builtin.get_url:
    url: https://pyenv.run
    dest: /tmp/install-pyenv.sh
    mode: '0740'

- name: Install pyenv using its script
  ignore_errors: yes
  shell: "/tmp/install-pyenv.sh"
  args:
    executable: /bin/bash
  failed_when: false

- name: Delete downloaded script
  ansible.builtin.file:
    path: /tmp/install-pyenv.sh
    state: absent

- name: Update list of installed applications (1/2)
  ansible.builtin.command: update-desktop-database ${HOME}/.local/share/applications

- name: Update list of installed applications (2/2)
  ansible.builtin.command: update-desktop-database ${HOME}/.local/share/flatpak/exports/share/applications

- name: Mouse highlight on ctrl
  ansible.builtin.command: gsettings set org.gnome.desktop.interface locate-pointer true

- name: Update Gnome Terminal shortcuts
  ansible.builtin.command: gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ next-tab '<Primary>Tab'

- name: Update Gnome Terminal shortcuts
  ansible.builtin.command: gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ prev-tab '<Primary><Shift>Tab'

- name: Configuring Gnome Evolution
  ansible.builtin.command: gsettings set org.gnome.evolution-data-server.calendar notify-with-tray true

- name: Configuring Gnome window settings
  ansible.builtin.command: gsettings set org.gnome.mutter center-new-windows true
  