---
# tasks file for gnome

- name: Install Gnome-specific packages
  become: yes
  become_method: sudo
  ansible.builtin.package:
    name: "{{ gnome_packages }}"
    state: latest

- name: Gnome terminal settings
  copy:
    src: gnome_terminal_settings_backup.dconf
    dest: ${HOME}/gnome_terminal_settings_backup.dconf
    mode: u=rwx,g=r,o=r

- name: Mouse highlight on ctrl
  ansible.builtin.command: gsettings set org.gnome.desktop.interface locate-pointer true

- name: Update Gnome Terminal shortcuts
  ansible.builtin.command: gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ next-tab '<Primary>Tab'

- name: Update Gnome Terminal shortcuts
  ansible.builtin.command: gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ prev-tab '<Primary><Shift>Tab'

- name: Configuring Gnome Evolution
  ansible.builtin.command: gsettings set org.gnome.evolution-data-server.calendar notify-with-tray true

- name: Configuring Gnome window settings
  ansible.builtin.command: gsettings set org.gnome.mutter center-new-windows true
  